// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr23S8Cdh1L7ZUGgeSdpXZHqrNLKZsY0g',
    appId: '1:623119011730:web:589875019a70303b85bb4b',
    messagingSenderId: '623119011730',
    projectId: 'stock-price-predictor-813d3',
    authDomain: 'stock-price-predictor-813d3.firebaseapp.com',
    storageBucket: 'stock-price-predictor-813d3.appspot.com',
    measurementId: 'G-5PZMWRTB7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANIPB0-aUWQI6aODNHioE_Ij2RXSnnQSg',
    appId: '1:623119011730:android:1b8786fe64da3c3f85bb4b',
    messagingSenderId: '623119011730',
    projectId: 'stock-price-predictor-813d3',
    storageBucket: 'stock-price-predictor-813d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-HOTvJDKoLkzjKJ39q9TK2MrYykf9L74',
    appId: '1:623119011730:ios:529d3f5bc9e9870285bb4b',
    messagingSenderId: '623119011730',
    projectId: 'stock-price-predictor-813d3',
    storageBucket: 'stock-price-predictor-813d3.appspot.com',
    iosClientId: '623119011730-mjsm4srr369hvciqbqm36lmp73psm3jd.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockPricePredictor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-HOTvJDKoLkzjKJ39q9TK2MrYykf9L74',
    appId: '1:623119011730:ios:529d3f5bc9e9870285bb4b',
    messagingSenderId: '623119011730',
    projectId: 'stock-price-predictor-813d3',
    storageBucket: 'stock-price-predictor-813d3.appspot.com',
    iosClientId: '623119011730-mjsm4srr369hvciqbqm36lmp73psm3jd.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockPricePredictor',
  );
}
